make precommit autofixable

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,7 +1,23 @@
 #!/bin/sh
 
-# Do not use husky, instead use git hooks directly. Husky quite unstable, espesialy with VSCode.
 # Do not modify .git/hooks/pre-commit directly. Instead, modify .hooks/pre-commit.
+
+# We do not use husky, instead use git hooks directly. 
+# Husky quite unstable, espesialy with VSCode.
+
+echo "Check if node is available"
+if ! command -v node >/dev/null 2>&1; then
+  export NVM_DIR="$HOME/.nvm"
+
+  echo "Node not found, attempt to set up nvm"
+  if [ ! -s "$NVM_DIR/nvm.sh" ]; then
+    echo "nvm is not installed, and node is not available. Will skip linting step."
+    exit 0
+  fi
+  . "$NVM_DIR/nvm.sh"  # Source nvm.sh to setup node environment
+fi
+echo "Expect node to be available"
+node -v
 
 # Run npx lint-staged
 echo "Running npx lint-staged..."
